### ISSUE TITLE
Module error

### ISSUE THREAD

**Issue by Freszmun** [intelligo-systems/neuro#59]
node app
D:\DESKTOP\proj31\node_modules\neuro.js\index.js:1
export const classifiers = require('./dist/core');
^^^^^^
SyntaxError: Unexpected token 'export'
[90m    at Module._compile (internal/modules/cjs/loader.js:881:18)[39m
[90m    at Object.Module._extensions..js (internal/modules/cjs/loader.js:962:10)[39m
[90m    at Module.load (internal/modules/cjs/loader.js:798:32)[39m
[90m    at Function.Module._load (internal/modules/cjs/loader.js:711:12)[39m
[90m    at Module.require (internal/modules/cjs/loader.js:838:19)[39m
[90m    at require (internal/modules/cjs/helpers.js:74:18)[39m
    at Object.<anonymous> (D:\DESKTOP\proj31\app.js:1:13)
[90m    at Module._compile (internal/modules/cjs/loader.js:945:30)[39m
[90m    at Object.Module._extensions..js (internal/modules/cjs/loader.js:962:10)[39m
[90m    at Module.load (internal/modules/cjs/loader.js:798:32)[39m

D:\DESKTOP\proj31>npm --version
6.11.3
D:\DESKTOP\proj31>node --version
v12.11.1

**Comment by CityArchitect** [comment]
Same problem as above; has this project been abandoned?

**Comment by Maxwell-Fisher** [comment]
I am also getting this error, has anyone been able to find a fix for it?

**Comment by Maxwell-Fisher** [comment]
`maxwell@maxwell-server-main:~/Desktop/test-ai$ node test.js
/home/maxwell/Desktop/test-ai/node_modules/neuro.js/index.js:1
(function (exports, require, module, __filename, __dirname) { export const classifiers = require('./dist/core');
                                                              ^^^^^^

SyntaxError: Unexpected token export
    at new Script (vm.js:79:7)
    at createScript (vm.js:251:10)
    at Object.runInThisContext (vm.js:303:10)
    at Module._compile (internal/modules/cjs/loader.js:657:28)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:700:10)
    at Module.load (internal/modules/cjs/loader.js:599:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:538:12)
    at Function.Module._load (internal/modules/cjs/loader.js:530:3)
    at Module.require (internal/modules/cjs/loader.js:637:17)
    at require (internal/modules/cjs/helpers.js:22:18)`

**Comment by georgeiliadis91** [comment]
This error persists, i tried to get into the source code and started changing imports and stuff. But seems like a wormhole of an issue.

Tried on windows and wsl2 ubuntu 20.4.

**Comment by raravel** [comment]
I temporarily solved it.

https://github.com/raravel/neuro-umd

**Comment by insancryptoroficial** [comment]
> I temporarily solved it.
> 
> https://github.com/raravel/neuro-umd

Can you tell me what the solution was?

**Comment by raravel** [comment]
> > I temporarily solved it.
> > https://github.com/raravel/neuro-umd
> 
> Can you tell me what the solution was?

I was just replace code `import` to `require`
